const express = require("express");
const routes = express.Router();

const homeRouter = require("./home");
const usersRouter = require("./users");
const stockRouter = require("./stock");
const queueRouter = require("./queue");
const userRouter = require("./user");
const homeAdminRouter = require("./homeAdmin");
const searchRouter = require("./search");
const analystRouter = require("./analyst");
const recordRouter = require("./record");
const sampleRouter = require("./sample");
const requisitionRouter = require("./requisition");
const profileRouter = require("./profile");
const allkitsRouter = require("./allkits");
const printtemplateRouter = require("./printtemplate");
const finalizationRouter = require("./finalization");
const previousmapRouter = require("./previousmap");
const reportRouter = require("./report");
const statisticsRouter = require("./statistics");
const covenantRouter = require("./covenant");

routes.use("/", homeRouter);
routes.use("/users", usersRouter);
routes.use("/queue", queueRouter);
routes.use("/requisition", requisitionRouter);
routes.use("/stock", stockRouter);
routes.use("/user", userRouter);
routes.use("/homeAdmin", homeAdminRouter);
routes.use("/search", searchRouter);
routes.use("/analyst", analystRouter);
routes.use("/sample", sampleRouter);
routes.use("/record", recordRouter);
routes.use("/profile", profileRouter);
routes.use("/allkits", allkitsRouter);
routes.use("/printtemplate", printtemplateRouter);
routes.use("/finalization", finalizationRouter);
routes.use("/report", reportRouter);
routes.use("/previousmap", previousmapRouter);
routes.use("/statistics", statisticsRouter);
routes.use("/covenant", covenantRouter);

module.exports = routes;
